# Generated by Django 5.2 on 2025-05-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
                ('docentes', models.ManyToManyField(to='Docentes.docente')),
            ],
        ),
    ]
