# Generated by Django 5.2 on 2025-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('funciones', models.TextField()),
                ('horario', models.CharField(max_length=500)),
                ('requisitos', models.TextField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
