# Generated by Django 5.2.1 on 2025-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0002_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Docentes'),
        ),
    ]
